name: MinetopiaPC
version: '2.1'
description: Computers voor jouw Minetopia server!
author: SBDeveloper
main: nl.SBDeveloper.MinetopiaPC.Main
depend: ['MinetopiaPC']
commands:
  computer:
    description: Open de computer!
    aliases: [mtpc, pc]
    permission: Computer.command